{{ if and (eq .Values.customAddon.enabled true) ( .Values.customAddon.externalPort) (.Values.customAddon.externalHost) }}

{{ if eq .Values.customAddon.dnsEnabled true }}
kind: Service
apiVersion: v1
metadata:
  name: service-external
spec:
  type: ExternalName
  externalName: {{ .Values.customAddon.externalHost }}
  ports:
    - name: http
      port: {{ .Values.customAddon.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.customAddon.externalPort }}
{{ else }}
kind: Service
apiVersion: v1
metadata:
  name: service-external
spec:
  ports:
    - port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: service-external
subsets:
  - addresses:
      - ip: {{ .Values.customAddon.externalHost }}
    ports:
      - port: {{ .Values.customAddon.externalPort }}
{{ end }}

{{ end }}
