apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tlsSecret.name }}
  namespace: {{ .Values.tlsSecret.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Values.tlsSecret.managedByLabel }}
  annotations:
    meta.helm.sh/release-name: {{ .Values.tlsSecret.releaseNameAnnotation }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.tlsSecret.certFile | b64enc | quote }}
  tls.key: {{ .Files.Get .Values.tlsSecret.keyFile | b64enc | quote }}


